# GitHub Action for Zernikalos-Studio CD (Release)

name: Create Release

# This workflow is triggered on pushes to tags that look like versions (e.g., v1.0.0)
on:
  # Trigger on tag push
  push:
    tags:
      - 'v*'

  # Allow manual trigger from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to create (e.g., v1.2.3). The associated Git tag must exist.'
        required: true

jobs:
  build:
    uses: ./.github/workflows/common-build.yml
    with:
      os: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    permissions:
      contents: read
      packages: read

  create-release:
    runs-on: ubuntu-latest
    needs: build # This job depends on the successful completion of the build job
    permissions:
      contents: write # Required to create the release

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: buildArtifacts # Download artifacts to a descriptive directory

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "buildArtifacts/**/*" # Upload all artifacts from all subdirectories
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.event.inputs.tag || github.ref_name }}
          releaseName: "Release ${{ github.event.inputs.tag || github.ref_name }}"
